export const FETCH_JOBS_REQUEST = "FETCH_JOBS_REQUEST";
export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS";
export const FETCH_JOBS_ERROR = "FETCH_JOBS_ERROR";

export const SELECT_JOB_REQUEST = "SELECT_JOB_REQUEST";
export const SELECT_JOB_SUCCESS = "SELECT_JOB_SUCCESS";
export const SELECT_JOB_ERROR = "SELECT_JOB_ERROR";
